// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfA1H1lf4P3EpnaGi3Iw3xNnjnWa9NSkc',
    appId: '1:808069311104:web:321f59d1bfddc766565465',
    messagingSenderId: '808069311104',
    projectId: 'smartexpensewallet',
    authDomain: 'smartexpensewallet.firebaseapp.com',
    storageBucket: 'smartexpensewallet.firebasestorage.app',
    measurementId: 'G-X4W9YV1TB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1qCtkY_p8vEeJan0t952brGXIcRaakc',
    appId: '1:808069311104:android:b64d37ee550715e8565465',
    messagingSenderId: '808069311104',
    projectId: 'smartexpensewallet',
    storageBucket: 'smartexpensewallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOWmhE5UefYSecaA_UDHR74sb1md3xt3I',
    appId: '1:808069311104:ios:4184a08886bd2269565465',
    messagingSenderId: '808069311104',
    projectId: 'smartexpensewallet',
    storageBucket: 'smartexpensewallet.firebasestorage.app',
    androidClientId: '808069311104-qpfeviur0rijlnl3v3trkpc8et6raueh.apps.googleusercontent.com',
    iosClientId: '808069311104-cc1v1t4ettilb7bsut5h44nstj1mcq72.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartExpenseWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOWmhE5UefYSecaA_UDHR74sb1md3xt3I',
    appId: '1:808069311104:ios:4184a08886bd2269565465',
    messagingSenderId: '808069311104',
    projectId: 'smartexpensewallet',
    storageBucket: 'smartexpensewallet.firebasestorage.app',
    androidClientId: '808069311104-qpfeviur0rijlnl3v3trkpc8et6raueh.apps.googleusercontent.com',
    iosClientId: '808069311104-cc1v1t4ettilb7bsut5h44nstj1mcq72.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartExpenseWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfA1H1lf4P3EpnaGi3Iw3xNnjnWa9NSkc',
    appId: '1:808069311104:web:28a0c0f51f6b1b76565465',
    messagingSenderId: '808069311104',
    projectId: 'smartexpensewallet',
    authDomain: 'smartexpensewallet.firebaseapp.com',
    storageBucket: 'smartexpensewallet.firebasestorage.app',
    measurementId: 'G-TDG4BMYXRY',
  );
}
